image: python:3.7
stages:
  - test

services:
  - postgres:11

variables:
  POSTGRES_DB: project_ci_test
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  TEST_DBNAME: '${CI_PROJECT_PATH_SLUG}-pipeline-${CI_PIPELINE_ID}'
  DEPLOY_DBNAME: '${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG}'
  RUNNER_HOME: '/home/gitlab-runner'
  INSTANCE_PATH: '${RUNNER_HOME}/instances/${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG}'
  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"
  VERSION: "11.0"
  ODOO_BRANCH: "11.0"
  ODOO_REPO: "odoo/odoo"


before_script:
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y  sudo postgresql-client expect-dev python3-lxml nodejs
    python3-pip build-essential libsasl2-dev python3-dev libldap2-dev libssl-dev
  - pip install coverage coveralls codecov

lint:
  stage: test
  tags:
    - postgres
    - docker
  variables:
    LINT_CHECK: "1"
    TESTS: "0"
  script:
    # We need to export the PG* here, otherwise the postgresql container
    # Wil pick them up
    - export PGHOST="postgres"
    - export PGUSER="odoo"
    - export PGPASSWORD=""
    - git clone -b master-forgeflow https://github.com/ForgeFlow/maintainer-quality-tools.git $HOME/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true

test:
  stage: test
  tags:
    - postgres
    - docker
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
    EXCLUDE: ""
  script:
    # We need to export the PG* here, otherwise the postgresql container
    # Wil pick them up
    - export PGHOST="postgres"
    - export PGUSER="odoo"
    - export PGPASSWORD=""
    - git clone -b master-forgeflow https://github.com/ForgeFlow/maintainer-quality-tools.git $HOME/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
